# -*- coding: utf-8 -*-
"""QuickHyre

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kC215vxjTy6e-yhUjLtveDEQn6kfTIlt
"""

# Cell 1 - Install dependencies
!pip install -q prophet pmdarima xgboost scikit-learn tensorflow pandas numpy matplotlib seaborn

# Cell 2 - Imports
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

from datetime import datetime, timedelta
print("Modules imported")

# Cell 3 - Load and parse data
df = pd.read_csv('/content/Forecasting_Dataset.csv')
df.columns = df.columns.str.strip()
df['Total'] = df['Total'].str.replace(',', '').str.strip().astype(float)
df['Date'] = pd.to_datetime(df['Date'], format='mixed', dayfirst=True)

print("Shape:", df.shape)
print("Date range:", df['Date'].min(), "to", df['Date'].max())
print("States:", df['State'].nunique())
print("Nulls:\n", df.isnull().sum())
print("\nSample:\n", df.head())

# Cell 4 - Sort and verify weekly consistency
df = df.sort_values(['State', 'Date']).reset_index(drop=True)

# Check number of observations per state
obs_per_state = df.groupby('State').size()
print("Observations per state:")
print(obs_per_state)
print("\nAll states have same number of observations:", obs_per_state.nunique() == 1)

# Check date gaps for one state as a sample
sample_state = df[df['State'] == 'Alabama'].copy()
sample_state['date_diff'] = sample_state['Date'].diff().dt.days
print("\nDate gaps in Alabama (should be ~7 days):")
print(sample_state['date_diff'].value_counts())

# Cell 4b - Fill missing dates and impute missing values
# For each state, reindex to a complete weekly grid and interpolate any gaps.
_all_states = df['State'].unique()
_filled = []

for _state in _all_states:
    _sdf = (
        df[df['State'] == _state]
        .copy()
        .set_index('Date')[['Total']]
    )
    # Build a complete weekly date range (same day-of-week as first observation)
    _full_range = pd.date_range(
        start=_sdf.index.min(),
        end=_sdf.index.max(),
        freq='7D'
    )
    _sdf = _sdf.reindex(_full_range)
    # Interpolate gaps, then fall back to forward/back fill at edges
    _sdf['Total'] = _sdf['Total'].interpolate(method='time').ffill().bfill()
    _sdf['State'] = _state
    _sdf.index.name = 'Date'
    _filled.append(_sdf.reset_index())

df = pd.concat(_filled, ignore_index=True)
df = df.sort_values(['State', 'Date']).reset_index(drop=True)
print(f"\nAfter gap-fill: shape={df.shape}")
print(f"Remaining nulls: {df.isnull().sum().sum()}")

# Cell 5 - EDA: National aggregate trend and sample state plots
# Aggregate all states to see overall trend
national = df.groupby('Date')['Total'].sum().reset_index()

plt.figure(figsize=(14, 4))
plt.plot(national['Date'], national['Total'])
plt.title('National Total Beverage Sales Over Time')
plt.xlabel('Date')
plt.ylabel('Total Sales')
plt.tight_layout()
plt.show()

# Plot 4 sample states to see individual behaviour
sample_states = ['California', 'Texas', 'New York', 'Florida']
fig, axes = plt.subplots(2, 2, figsize=(14, 8))
axes = axes.flatten()

for i, state in enumerate(sample_states):
    state_df = df[df['State'] == state]
    axes[i].plot(state_df['Date'], state_df['Total'])
    axes[i].set_title(state)
    axes[i].set_xlabel('Date')
    axes[i].set_ylabel('Total Sales')

plt.tight_layout()
plt.show()

# Cell 6 - Train/validation split per state
# Hold out last 16 weeks as validation, rest is training
FORECAST_HORIZON = 8
VAL_SIZE = 16

states = df['State'].unique()
state_dfs = {}

for state in states:
    state_df = df[df['State'] == state].sort_values('Date').reset_index(drop=True)
    state_df = state_df[['Date', 'Total']]
    train = state_df.iloc[:-VAL_SIZE]
    val = state_df.iloc[-VAL_SIZE:]
    state_dfs[state] = {'full': state_df, 'train': train, 'val': val}

# Confirm split for one state
sample = state_dfs['California']
print("California train size:", len(sample['train']))
print("California val size:", len(sample['val']))
print("Train ends:", sample['train']['Date'].iloc[-1])
print("Val starts:", sample['val']['Date'].iloc[0])
print("Val ends:", sample['val']['Date'].iloc[-1])

# Cell 7 - Feature Engineering
from pandas.tseries.holiday import USFederalHolidayCalendar as _USCal

def create_features(df, label_col='Total'):
    df = df.copy()
    df = df.sort_values('Date').reset_index(drop=True)

    # Calendar features
    df['week_of_year'] = df['Date'].dt.isocalendar().week.astype(int)
    df['month'] = df['Date'].dt.month
    df['quarter'] = df['Date'].dt.quarter
    df['year'] = df['Date'].dt.year

    # Day-of-week (0 = Monday … 6 = Sunday)
    df['day_of_week'] = df['Date'].dt.dayofweek

    # Holiday flag: 1 if any US federal holiday falls within the 7-day week
    # starting on the row's date, 0 otherwise
    _cal = _USCal()
    _holidays = _cal.holidays(
        start=df['Date'].min(),
        end=df['Date'].max() + pd.Timedelta(days=6)
    )
    df['is_holiday'] = df['Date'].apply(
        lambda d: int(
            any(_holidays.isin(pd.date_range(d, periods=7, freq='D')))
        )
    )

    # Lag features (in weekly data: 1 week, 7 weeks, 30 weeks back)
    df['lag_1'] = df[label_col].shift(1)
    df['lag_7'] = df[label_col].shift(7)
    df['lag_30'] = df[label_col].shift(30)

    # Rolling statistics (window in weeks)
    df['rolling_mean_4'] = df[label_col].shift(1).rolling(window=4).mean()
    df['rolling_mean_8'] = df[label_col].shift(1).rolling(window=8).mean()
    df['rolling_std_4'] = df[label_col].shift(1).rolling(window=4).std()

    # Drop rows where lags are NaN (first 30 rows per state)
    df = df.dropna().reset_index(drop=True)

    return df

# Apply to all states and verify
sample_featured = create_features(state_dfs['California']['full'])
print("Featured dataframe shape:", sample_featured.shape)
print("Columns:", sample_featured.columns.tolist())
print("\nSample:\n", sample_featured.head(3))

# Cell 8 - Apply features to all states and rebuild splits
featured_state_dfs = {}

for state in states:
    full_df = state_dfs[state]['full']
    featured = create_features(full_df)

    # Rebuild train/val split on featured df (last 16 rows as val)
    train = featured.iloc[:-VAL_SIZE].reset_index(drop=True)
    val = featured.iloc[-VAL_SIZE:].reset_index(drop=True)

    featured_state_dfs[state] = {
        'full': featured,
        'train': train,
        'val': val
    }

# Verify
sample = featured_state_dfs['California']
print("States processed:", len(featured_state_dfs))
print("California featured train size:", len(sample['train']))
print("California featured val size:", len(sample['val']))
print("Feature columns:", sample['full'].columns.tolist())

# Cell 9 - ARIMA/SARIMA training and evaluation
from pmdarima import auto_arima
from sklearn.metrics import mean_absolute_error, mean_squared_error

def train_arima(train_series, val_series):
    model = auto_arima(
        train_series,
        seasonal=True,
        m=52,                  # weekly seasonality
        stepwise=True,
        suppress_warnings=True,
        error_action='ignore',
        max_p=3, max_q=3,
        max_P=1, max_Q=1,
        d=None,                # auto-detect differencing
        information_criterion='aic',
        n_jobs=-1
    )

    # Forecast val_size steps ahead
    forecast = model.predict(n_periods=len(val_series))

    mae = mean_absolute_error(val_series, forecast)
    rmse = np.sqrt(mean_squared_error(val_series, forecast))
    mape = np.mean(np.abs((val_series - forecast) / val_series)) * 100

    return model, forecast, {'MAE': mae, 'RMSE': rmse, 'MAPE': mape}

# Test on California first
print("Training ARIMA for California...")
ca_train = featured_state_dfs['California']['train']['Total'].values
ca_val = featured_state_dfs['California']['val']['Total'].values

arima_model, arima_forecast, arima_metrics = train_arima(ca_train, ca_val)
print("ARIMA Metrics for California:")
print(f"  MAE:  {arima_metrics['MAE']:,.0f}")
print(f"  RMSE: {arima_metrics['RMSE']:,.0f}")
print(f"  MAPE: {arima_metrics['MAPE']:.2f}%")

# Cell 10 - Prophet training and evaluation
from prophet import Prophet

def train_prophet(train_df, val_df):
    # Prophet requires columns named ds and y
    prophet_train = train_df[['Date', 'Total']].rename(columns={'Date': 'ds', 'Total': 'y'})

    model = Prophet(
        yearly_seasonality=True,
        weekly_seasonality=False,
        daily_seasonality=False,
        seasonality_mode='multiplicative'
    )
    model.fit(prophet_train)

    # Create future dataframe for val period
    future = pd.DataFrame({'ds': val_df['Date'].values})
    forecast = model.predict(future)['yhat'].values

    val_series = val_df['Total'].values
    mae = mean_absolute_error(val_series, forecast)
    rmse = np.sqrt(mean_squared_error(val_series, forecast))
    mape = np.mean(np.abs((val_series - forecast) / val_series)) * 100

    return model, forecast, {'MAE': mae, 'RMSE': rmse, 'MAPE': mape}

# Test on California
print("Training Prophet for California...")
ca_train_df = featured_state_dfs['California']['train']
ca_val_df = featured_state_dfs['California']['val']

prophet_model, prophet_forecast, prophet_metrics = train_prophet(ca_train_df, ca_val_df)
print("Prophet Metrics for California:")
print(f"  MAE:  {prophet_metrics['MAE']:,.0f}")
print(f"  RMSE: {prophet_metrics['RMSE']:,.0f}")
print(f"  MAPE: {prophet_metrics['MAPE']:.2f}%")

# Cell 11 - XGBoost training and evaluation
from xgboost import XGBRegressor
from sklearn.preprocessing import StandardScaler

FEATURE_COLS = ['week_of_year', 'month', 'quarter', 'year',
                'day_of_week', 'is_holiday',
                'lag_1', 'lag_7', 'lag_30',
                'rolling_mean_4', 'rolling_mean_8', 'rolling_std_4']

def train_xgboost(train_df, val_df):
    X_train = train_df[FEATURE_COLS].values
    y_train = train_df['Total'].values
    X_val = val_df[FEATURE_COLS].values
    y_val = val_df['Total'].values

    scaler = StandardScaler()
    X_train_scaled = scaler.fit_transform(X_train)
    X_val_scaled = scaler.transform(X_val)

    model = XGBRegressor(
        n_estimators=300,
        learning_rate=0.05,
        max_depth=4,
        subsample=0.8,
        colsample_bytree=0.8,
        random_state=42,
        verbosity=0
    )
    model.fit(X_train_scaled, y_train)
    forecast = model.predict(X_val_scaled)

    mae = mean_absolute_error(y_val, forecast)
    rmse = np.sqrt(mean_squared_error(y_val, forecast))
    mape = np.mean(np.abs((y_val - forecast) / y_val)) * 100

    return model, scaler, forecast, {'MAE': mae, 'RMSE': rmse, 'MAPE': mape}

# Test on California
print("Training XGBoost for California...")
xgb_model, xgb_scaler, xgb_forecast, xgb_metrics = train_xgboost(ca_train_df, ca_val_df)
print("XGBoost Metrics for California:")
print(f"  MAE:  {xgb_metrics['MAE']:,.0f}")
print(f"  RMSE: {xgb_metrics['RMSE']:,.0f}")
print(f"  MAPE: {xgb_metrics['MAPE']:.2f}%")

# Cell 12 - LSTM training and evaluation
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense, Dropout
from tensorflow.keras.callbacks import EarlyStopping
from sklearn.preprocessing import MinMaxScaler

SEQUENCE_LENGTH = 12  # use last 12 weeks to predict next week

def create_sequences(data, seq_length):
    X, y = [], []
    for i in range(len(data) - seq_length):
        X.append(data[i:i+seq_length])
        y.append(data[i+seq_length])
    return np.array(X), np.array(y)

def train_lstm(train_df, val_df):
    train_values = train_df['Total'].values.reshape(-1, 1)
    val_values = val_df['Total'].values.reshape(-1, 1)

    scaler = MinMaxScaler()
    train_scaled = scaler.fit_transform(train_values)
    val_scaled = scaler.transform(val_values)

    # Combine for sequence creation, then split
    full_scaled = np.concatenate([train_scaled, val_scaled])
    X, y = create_sequences(full_scaled, SEQUENCE_LENGTH)

    X_train = X[:len(train_scaled) - SEQUENCE_LENGTH]
    y_train = y[:len(train_scaled) - SEQUENCE_LENGTH]
    X_val = X[len(train_scaled) - SEQUENCE_LENGTH:]
    y_val = y[len(train_scaled) - SEQUENCE_LENGTH:]

    model = Sequential([
        LSTM(64, input_shape=(SEQUENCE_LENGTH, 1), return_sequences=True),
        Dropout(0.2),
        LSTM(32),
        Dropout(0.2),
        Dense(1)
    ])
    model.compile(optimizer='adam', loss='mse')

    early_stop = EarlyStopping(patience=10, restore_best_weights=True)
    model.fit(X_train, y_train,
              epochs=100,
              batch_size=16,
              validation_data=(X_val, y_val),
              callbacks=[early_stop],
              verbose=0)

    forecast_scaled = model.predict(X_val, verbose=0)
    forecast = scaler.inverse_transform(forecast_scaled).flatten()
    y_val_actual = scaler.inverse_transform(y_val.reshape(-1, 1)).flatten()

    mae = mean_absolute_error(y_val_actual, forecast)
    rmse = np.sqrt(mean_squared_error(y_val_actual, forecast))
    mape = np.mean(np.abs((y_val_actual - forecast) / y_val_actual)) * 100

    return model, scaler, forecast, {'MAE': mae, 'RMSE': rmse, 'MAPE': mape}

# Test on California
print("Training LSTM for California...")
lstm_model, lstm_scaler, lstm_forecast, lstm_metrics = train_lstm(ca_train_df, ca_val_df)
print("LSTM Metrics for California:")
print(f"  MAE:  {lstm_metrics['MAE']:,.0f}")
print(f"  RMSE: {lstm_metrics['RMSE']:,.0f}")
print(f"  MAPE: {lstm_metrics['MAPE']:.2f}%")

# Cell 13 - Compare all models for California and plot forecasts
ca_val_dates = ca_val_df['Date'].values
ca_val_actual = ca_val_df['Total'].values

results_ca = {
    'ARIMA':    {'metrics': arima_metrics,   'forecast': arima_forecast},
    'Prophet':  {'metrics': prophet_metrics, 'forecast': prophet_forecast},
    'XGBoost':  {'metrics': xgb_metrics,     'forecast': xgb_forecast},
    'LSTM':     {'metrics': lstm_metrics,    'forecast': lstm_forecast},
}

print("Model Comparison - California")
print(f"{'Model':<12} {'MAE':>15} {'RMSE':>15} {'MAPE':>8}")
print("-" * 55)
for model_name, res in results_ca.items():
    m = res['metrics']
    print(f"{model_name:<12} {m['MAE']:>15,.0f} {m['RMSE']:>15,.0f} {m['MAPE']:>7.2f}%")

# Plot all forecasts vs actual
plt.figure(figsize=(14, 5))
plt.plot(ca_val_dates, ca_val_actual, label='Actual', linewidth=2, color='black')
for model_name, res in results_ca.items():
    plt.plot(ca_val_dates, res['forecast'], label=model_name, linestyle='--')
plt.title('California - Model Forecast Comparison (Validation Period)')
plt.xlabel('Date')
plt.ylabel('Total Sales')
plt.legend()
plt.tight_layout()
plt.show()

# Cell 14 - Train all models for all 43 states
import time

all_results = {}

for i, state in enumerate(states):
    print(f"[{i+1}/43] Training models for {state}...")
    train_df = featured_state_dfs[state]['train']
    val_df = featured_state_dfs[state]['val']

    train_series = train_df['Total'].values
    val_series = val_df['Total'].values

    state_result = {}

    # ARIMA
    try:
        m, f, metrics = train_arima(train_series, val_series)
        state_result['ARIMA'] = {'model': m, 'forecast': f, 'metrics': metrics}
    except Exception as e:
        print(f"  ARIMA failed: {e}")

    # Prophet
    try:
        m, f, metrics = train_prophet(train_df, val_df)
        state_result['Prophet'] = {'model': m, 'forecast': f, 'metrics': metrics}
    except Exception as e:
        print(f"  Prophet failed: {e}")

    # XGBoost
    try:
        m, scaler, f, metrics = train_xgboost(train_df, val_df)
        state_result['XGBoost'] = {'model': m, 'scaler': scaler, 'forecast': f, 'metrics': metrics}
    except Exception as e:
        print(f"  XGBoost failed: {e}")

    # LSTM
    try:
        m, scaler, f, metrics = train_lstm(train_df, val_df)
        state_result['LSTM'] = {'model': m, 'scaler': scaler, 'forecast': f, 'metrics': metrics}
    except Exception as e:
        print(f"  LSTM failed: {e}")

    all_results[state] = state_result

print("\nAll states done.")

# Cell 15 - Model selection: pick best model per state based on MAPE
model_registry = {}

print(f"{'State':<20} {'Best Model':<12} {'MAPE':>8}")
print("-" * 45)

for state, results in all_results.items():
    best_model_name = None
    best_mape = float('inf')

    for model_name, result in results.items():
        mape = result['metrics']['MAPE']
        if mape < best_mape:
            best_mape = mape
            best_model_name = model_name

    model_registry[state] = {
        'best_model': best_model_name,
        'metrics': {
            model_name: result['metrics']
            for model_name, result in results.items()
        }
    }
    print(f"{state:<20} {best_model_name:<12} {best_mape:>7.2f}%")

# Summary of how many states each model won
from collections import Counter
winner_counts = Counter(v['best_model'] for v in model_registry.values())
print("\nModel win counts across 43 states:")
for model_name, count in winner_counts.most_common():
    print(f"  {model_name}: {count} states")

# Cell 16 - Save model registry as JSON
import json

# Build a JSON-serialisable version of the registry
registry_json = {}
for state, info in model_registry.items():
    registry_json[state] = {
        'best_model': info['best_model'],
        'metrics': {
            model_name: {k: round(v, 4) for k, v in metrics.items()}
            for model_name, metrics in info['metrics'].items()
        }
    }

with open('model_registry.json', 'w') as f:
    json.dump(registry_json, f, indent=2)

print("model_registry.json saved.")
print("Sample entry:")
print(json.dumps(registry_json['California'], indent=2))

# Cell 17 - Export winning models to files
import joblib
import os

os.makedirs('models', exist_ok=True)

for state, info in model_registry.items():
    best = info['best_model']
    result = all_results[state][best]
    safe_state = state.replace(' ', '_')

    if best == 'ARIMA':
        joblib.dump(result['model'], f'models/{safe_state}_ARIMA.pkl')

    elif best == 'Prophet':
        joblib.dump(result['model'], f'models/{safe_state}_Prophet.pkl')

    elif best == 'XGBoost':
        result['model'].save_model(f'models/{safe_state}_XGBoost.json')
        joblib.dump(result['scaler'], f'models/{safe_state}_XGBoost_scaler.pkl')

    elif best == 'LSTM':
        result['model'].save(f'models/{safe_state}_LSTM.keras')
        joblib.dump(result['scaler'], f'models/{safe_state}_LSTM_scaler.pkl')

print("All winning models saved.")
print("Files in models/:")
for f in sorted(os.listdir('models')):
    print(f" {f}")

# Cell 18 - Generate 8-week future forecasts for all states
from pandas.tseries.offsets import Week

FORECAST_HORIZON = 8

def forecast_future_xgboost(state, model_path, scaler_path, n=8):
    from xgboost import XGBRegressor
    model = XGBRegressor()
    model.load_model(model_path)
    scaler = joblib.load(scaler_path)

    full_df = featured_state_dfs[state]['full'].copy()
    history = full_df['Total'].tolist()
    last_date = full_df['Date'].iloc[-1]

    preds = []
    for i in range(n):
        next_date = last_date + pd.Timedelta(weeks=i+1)
        lag_1  = history[-1]
        lag_7  = history[-7] if len(history) >= 7 else history[0]
        lag_30 = history[-30] if len(history) >= 30 else history[0]
        roll4  = np.mean(history[-4:])
        roll8  = np.mean(history[-8:])
        std4   = np.std(history[-4:])

        features = np.array([[
            next_date.isocalendar()[1],
            next_date.month,
            next_date.quarter,
            next_date.year,
            lag_1, lag_7, lag_30,
            roll4, roll8, std4
        ]])
        features_scaled = scaler.transform(features)
        pred = model.predict(features_scaled)[0]
        preds.append((next_date.strftime('%Y-%m-%d'), round(float(pred), 2)))
        history.append(pred)

    return preds

def forecast_future_arima(state, model_path, n=8):
    model = joblib.load(model_path)
    preds_values = model.predict(n_periods=n)
    full_df = featured_state_dfs[state]['full']
    last_date = full_df['Date'].iloc[-1]
    dates = [(last_date + pd.Timedelta(weeks=i+1)).strftime('%Y-%m-%d') for i in range(n)]
    return list(zip(dates, [round(float(v), 2) for v in preds_values]))

def forecast_future_prophet(state, model_path, n=8):
    model = joblib.load(model_path)
    full_df = featured_state_dfs[state]['full']
    last_date = full_df['Date'].iloc[-1]
    future_dates = [last_date + pd.Timedelta(weeks=i+1) for i in range(n)]
    future_df = pd.DataFrame({'ds': future_dates})
    forecast = model.predict(future_df)['yhat'].values
    dates = [d.strftime('%Y-%m-%d') for d in future_dates]
    return list(zip(dates, [round(float(v), 2) for v in forecast]))

def forecast_future_lstm(state, model_path, scaler_path, n=8):
    from tensorflow.keras.models import load_model
    model = load_model(model_path)
    scaler = joblib.load(scaler_path)

    full_df = featured_state_dfs[state]['full']
    last_date = full_df['Date'].iloc[-1]
    history = full_df['Total'].values.tolist()

    preds = []
    sequence = list(scaler.transform(np.array(history[-SEQUENCE_LENGTH:]).reshape(-1,1)).flatten())

    for i in range(n):
        next_date = last_date + pd.Timedelta(weeks=i+1)
        x = np.array(sequence[-SEQUENCE_LENGTH:]).reshape(1, SEQUENCE_LENGTH, 1)
        pred_scaled = model.predict(x, verbose=0)[0][0]
        pred = scaler.inverse_transform([[pred_scaled]])[0][0]
        preds.append((next_date.strftime('%Y-%m-%d'), round(float(pred), 2)))
        sequence.append(pred_scaled)

    return preds

# Generate forecasts for all states
future_forecasts = {}

for state, info in model_registry.items():
    best = info['best_model']
    safe_state = state.replace(' ', '_')

    if best == 'XGBoost':
        preds = forecast_future_xgboost(
            state,
            f'models/{safe_state}_XGBoost.json',
            f'models/{safe_state}_XGBoost_scaler.pkl'
        )
    elif best == 'ARIMA':
        preds = forecast_future_arima(state, f'models/{safe_state}_ARIMA.pkl')
    elif best == 'Prophet':
        preds = forecast_future_prophet(state, f'models/{safe_state}_Prophet.pkl')
    elif best == 'LSTM':
        preds = forecast_future_lstm(
            state,
            f'models/{safe_state}_LSTM.keras',
            f'models/{safe_state}_LSTM_scaler.pkl'
        )

    future_forecasts[state] = [{'date': d, 'forecast': v} for d, v in preds]
    print(f"{state} ({best}) - first forecast: {preds[0]}")

print("\nAll future forecasts generated.")

# Cell 19 - Save future forecasts to JSON
with open('forecasts.json', 'w') as f:
    json.dump(future_forecasts, f, indent=2)

print("forecasts.json saved.")
print(f"Total states: {len(future_forecasts)}")
print("\nSample - California 8-week forecast:")
for entry in future_forecasts['California']:
    print(f"  {entry['date']}: {entry['forecast']:,.0f}")

# Cell 20 - Download all files for local API
from google.colab import files
import zipfile
import os

# Zip models folder and both json files together
with zipfile.ZipFile('api_assets.zip', 'w') as zipf:
    # Add model files
    for fname in os.listdir('models'):
        zipf.write(f'models/{fname}', f'models/{fname}')
    # Add registry and forecasts
    zipf.write('model_registry.json')
    zipf.write('forecasts.json')

print("api_assets.zip created.")
print("Contents:")
with zipfile.ZipFile('api_assets.zip', 'r') as z:
    for name in sorted(z.namelist()):
        print(f"  {name}")

files.download('api_assets.zip')

